#!/bin/bash

#instanceip=$(curl http://169.254.169.254/latest/meta-data/public-ipv4)

# Updating server OS
sudo yum update -y

# Installing and configuring a webserver
sudo yum install epel-release -y
sudo yum install nginx -y

sudo systemctl start nginx
sudo systemctl enable nginx

sudo timedatectl set-timezone America/Sao_Paulo
sudo echo $HOSTNAME >> /usr/share/doc/HTML/index.html

#sudo firewall-cmd --permanent --zone=public --add-service=http 
#sudo firewall-cmd --permanent --zone=public --add-service=https
sudo firewall-offline-cmd --add-service=http 
sudo firewall-offline-cmd --add-service=https

sudo firewall-cmd --reload
#sudo systemctl restart firewalld
